# This network policy together with the Alpine-telnet deployment manifest 
# will be used for testing connectivity between internal and external 
# service. Make sure you add the appropriate outbound and inbound 
# rule for your communication. Use the telnet values to make changes
# if you want to test a new server and port

{{- if .Values.telnet.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-telnet
  labels:
    app: {{ include "chart.fullname" . }}-telnet
    {{- include "common.labels" .Values.telnet.commonLabels }}
  annotations: 
    datree.skip/CUSTOM_REPLICA_COUNT_PROD: skip for default helm.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "chart.fullname" . }}-telnet
  template:
    metadata:
      labels:
        app: {{ include "chart.fullname" . }}-telnet
        {{- include "common.labels" .Values.telnet.commonLabels | nindent 4 }}
    spec:
      containers:
        - name: telnet-container
          image: sookeke/alpine-telnet:v1
          imagePullPolicy: Always
          args: ["sh", "-c", "while true; do telnet {{ .Values.telnet.goldService }} {{ .Values.telnet.goldPort }}; telnet {{ .Values.telnet.diamSSO }} {{ .Values.telnet.diamPort }}; curl -v {{ .Values.telnet.publicService }}; git clone {{ .Values.telnet.gitHubUrl }}; sleep 45; done"]
          resources:
            limits:
              cpu: "10m"
              memory: "100Mi"
            requests:
              cpu: "2m"
              memory: "20Mi"
          env:
            - name: HTTP_PROXY
              value: "http://swpxkam.gov.bc.ca:8080"
            - name: HTTPS_PROXY
              value: "http://swpxkam.gov.bc.ca:8080"
            - name: NO_PROXY
              value: .cluster.local,.svc,10.91.0.0/16,172.30.0.0/16,127.0.0.1,localhost,.gov.bc.ca
          volumeMounts:
            - name: data-volume
              mountPath: /home/myuser
          livenessProbe:
            exec:
              command:
                - "telnet"
                - "{{ .Values.telnet.goldService }}"
                - "{{ .Values.telnet.goldPort }}"
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - "telnet"
                - "{{ .Values.telnet.goldService }}"
                - "{{ .Values.telnet.goldPort }}"
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data-volume
          emptyDir: {}
{{- end }}
