apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name:  {{ include "react-baseapp.fullname" . }}
  labels:
     {{- include "react-baseapp.labels" . | nindent 4 }}
  annotations:
      {{- with .Values.route.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name:  {{ include "react-baseapp.fullname" . }}
  port:
    targetPort: nginxport
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
