

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ "{{" }} include "chart.fullname" . {{ "}}" }}-backup-egress
  labels:
    app.kubernetes.io/component: pg_dumpall
    role: backup
  annotations: 
    datree.skip/CUSTOM_WORKLOAD_INCORRECT_NETWORK_POLICIES: skipping this policy
    datree.skip/CUSTOM_WORKLOAD_INVALID_LABELS_VALUE: skipping this policy
    datree.skip/CUSTOM_WORKLOAD_INCORRECT_ENVIRONMENT_LABELS: skipping this policy
    datree.skip/CUSTOM_WORKLOAD_MISSING_LABEL_OWNER_VALUE: skipping this policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: pg_dumpall
      job: postgres-job
  egress:
    - {}
  policyTypes:
    - Egress

