project: e56h79
kind: Application
metadata:
  name: e56h79-app-gitops-prod
spec:
  destination:
    name: ''
    namespace: e56h79-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/gitops
    repoURL: 'git@github.com:bcgov-c/tenant-gitops-e56h79.git'
    targetRevision: main
    helm:
      valueFiles:
        - $values/deploy/prod_values.yaml
  project: e56h79
  syncPolicy:
    automated:
      prune: true
      selfHeal: true